-- Add all missing columns to profiles table
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS display_name TEXT,
  ADD COLUMN IF NOT EXISTS telegram_username TEXT,
  ADD COLUMN IF NOT EXISTS telegram_first_name TEXT,
  ADD COLUMN IF NOT EXISTS telegram_last_name TEXT,
  
  ADD COLUMN IF NOT EXISTS bz_balance BIGINT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS bb_balance NUMERIC(20,6) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS xp BIGINT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'Bronze' NOT NULL,
  
  ADD COLUMN IF NOT EXISTS current_energy NUMERIC(10,2) DEFAULT 1500 NOT NULL,
  ADD COLUMN IF NOT EXISTS max_energy NUMERIC(10,2) DEFAULT 1500 NOT NULL,
  ADD COLUMN IF NOT EXISTS energy_recovery_rate NUMERIC(10,2) DEFAULT 0.3 NOT NULL,
  ADD COLUMN IF NOT EXISTS last_energy_update TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  
  ADD COLUMN IF NOT EXISTS booster_income_per_tap INTEGER DEFAULT 1 NOT NULL,
  ADD COLUMN IF NOT EXISTS booster_energy_per_tap INTEGER DEFAULT 1 NOT NULL,
  ADD COLUMN IF NOT EXISTS booster_energy_capacity INTEGER DEFAULT 1 NOT NULL,
  ADD COLUMN IF NOT EXISTS booster_recovery_rate INTEGER DEFAULT 1 NOT NULL,
  
  ADD COLUMN IF NOT EXISTS quickcharge_uses_remaining INTEGER DEFAULT 5 NOT NULL,
  ADD COLUMN IF NOT EXISTS quickcharge_last_reset TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  ADD COLUMN IF NOT EXISTS quickcharge_cooldown_until TIMESTAMP WITH TIME ZONE,
  
  ADD COLUMN IF NOT EXISTS last_claim_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  ADD COLUMN IF NOT EXISTS active_build_part_id TEXT,
  ADD COLUMN IF NOT EXISTS active_build_end_time TIMESTAMP WITH TIME ZONE,
  
  ADD COLUMN IF NOT EXISTS referred_by_code TEXT,
  ADD COLUMN IF NOT EXISTS total_referrals INTEGER DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS referral_milestone_5_claimed BOOLEAN DEFAULT FALSE NOT NULL,
  ADD COLUMN IF NOT EXISTS referral_milestone_10_claimed BOOLEAN DEFAULT FALSE NOT NULL,
  ADD COLUMN IF NOT EXISTS referral_milestone_25_claimed BOOLEAN DEFAULT FALSE NOT NULL,
  ADD COLUMN IF NOT EXISTS referral_milestone_50_claimed BOOLEAN DEFAULT FALSE NOT NULL,
  
  ADD COLUMN IF NOT EXISTS daily_reward_streak INTEGER DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS daily_reward_last_claim TIMESTAMP WITH TIME ZONE,
  
  ADD COLUMN IF NOT EXISTS nfts_owned TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
  
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL;